config/routes.rb
Rails.application.routes.draw do
  
  resources :users
  resources :microposts
   
  # get   "/users", to: "users#index"
  # get   "/users/:id", to: "users#show"
  # get   "/users/:new", to: "users#new"
  # post  "users", to: "users#create"
  # put   "users/:id", to: "users#edit"
  # patch "users/:id", to: "users#update"
  # delete  "users/:id", to: "users#destroy"
end
  
               

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/micropost.rb
class Micropost < ApplicationRecord
  validates :content, presence: true
  validates :content, uniqueness: true, presence: true
  belongs_to :user
end

app/models/user.rb
class User < ApplicationRecord
  validates :name, presence: true
  # validates :email, format: { with: /\A[a-zA-Z]+\z/}
  validate :email
  has_many :microposts
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/microposts_controller.rb
class MicropostsController < ApplicationController
  def index 
    @microposts = Micropost.all
  end
  def show
    @micropost = Micropost.find(params[:id])
  end

  def new
    @micropost = Micropost.new
  end

   def create
    @micropost = Micropost.new(micropost_params)

    if @micropost.save
      redirect_to @micropost
    else
      render :new, status: :unprocessable_entity
    end
  end

  def edit
    @micropost = Micropost.find(params[:id])
  end

  def update
    @micropost = Micropost.find(params[:id])

    if @micropost.update(micropost_params)
      redirect_to @micropost
    else
      render :edit, status: :unprocessable_entity
    end
  end



  def destroy
    @micropost = Micropost.find(params[:id])
    @micropost.destroy

    redirect_to root_path, status: :see_other
  end



    private
    def micropost_params
      params.require(:micropost).permit(:content, :user_id)
    end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController

  def index 
    @users = User.all
  end
  def show
    @user = User.find(params[:id])
  end

  def new
    @user = User.new
  end

   def create
    @user = User.new(user_params)

    if @user.save
      redirect_to @user
    else
      render :new, status: :unprocessable_entity
    end
  end


  def edit
    @user = User.find(params[:id])
  end

  def update
    @user = User.find(params[:id])

    if @user.update(user_params)
      redirect_to @user
    else
      render :edit, status: :unprocessable_entity
    end
  end



  def destroy
    @user = User.find(params[:id])
    @user.destroy

    redirect_to root_path, status: :see_other
  end



    private
    def user_params
      params.require(:user).permit(:name, :email)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/microposts_helper.rb
module MicropostsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>ToyApp</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    
  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/microposts/_form.html.erb
<%= form_with(model: micropost) do |form| %>
  <% if micropost.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(micropost.errors.count, "error") %> prohibited this micropost from being saved:</h2>

      <ul>
        <% micropost.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :content %>
    <%= form.text_area :content %>
  </div>

  <div class="field">
    <%= form.label :user_id %>
    <%= form.number_field :user_id %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/microposts/edit.html.erb
<h1>Editing Micropost</h1>

<%= render 'form', micropost: @micropost %>

<%= link_to 'Show', @micropost %> |
<%= link_to 'Back', microposts_path %>

app/views/microposts/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Microposts</h1>

<table>
  <thead>
    <tr>
      <th>Content</th>
      <th>User</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @microposts.each do |micropost| %>
      <tr>
        <td><%= micropost.content %></td>
        <td><%= micropost.user_id %></td>
        <td><%= link_to 'Show', micropost %></td>
        <td><%= link_to 'Edit', edit_micropost_path(micropost) %></td>
        <td><%= link_to 'Destroy', micropost, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Micropost', new_micropost_path %>

app/views/microposts/new.html.erb
<h1>New Micropost</h1>

<%= render 'form', micropost: @micropost %>

<%= link_to 'Back', microposts_path %>

app/views/microposts/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Content:</strong>
  <%= @micropost.content %>
</p>

<p>
  <strong>User:</strong>
  <%= @micropost.user_id %>
</p>

<%= link_to 'Edit', edit_micropost_path(@micropost) %> |
<%= link_to 'Back', microposts_path %>

app/views/users/_form.html.erb
<%= form_with model: user do |form| %>
  <div>
    <%= form.label :name %><br>
    <%= form.text_field :name %>
    <% user.errors.full_messages_for(:name).each do |message| %>
      <div><%= message %></div>
    <% end %>
  </div>

  <div>
    <%= form.label :email %><br>
    <%= form.text_area :email %><br>
    <% user.errors.full_messages_for(:email).each do |message| %>
      <div><%= message %></div>
    <% end %>
  </div>

  <div>
    <%= form.submit %>
  </div>
<% end %>

app/views/users/edit.html.erb
<h1>Edit User</h1>

<%= render "form", user: @user %>

app/views/users/index.html.erb
<h1>Users</h1>

<ul>
  <% @users.each do |user| %>
    <li>
       <%= link_to user.name, user %>
    </li>
  <% end %>
</ul>

<%= link_to "New User", new_user_path %> 

app/views/users/new.html.erb
<h1>New User</h1>

<%= render "form", user: @user %>

app/views/users/show.html.erb
<h1><%= @user.name %></h1>

<p><%= @user.email %></p>


<ul>
  <li><%= link_to "Edit", edit_user_path(@user) %></li>
  <li><%= link_to "Destroy", user_path(@user), data: {
                    turbo_method: :delete,
                    turbo_confirm: "Are you sure?"
                  } %></li>
</ul>